### ISSUE TITLE
The index Route has no Server Side Rendering 

### ISSUE THREAD

**Issue by gionatan-lombardi** [dai-shi/express-react-redux#6]
I've started to use this library, but the Index Route ('/') has no Server Side Rendering. Why? All the others Routes are rendered fine.
This can be a big problem for SEO reasons (the homepage is usually the most important page).
Probably there's a good reason I can't figure out.

**Comment by dai-shi** [comment]
Is the file name `index.html`? If not, you need to add a configuration.

**Comment by dai-shi** [comment]
Oh, you are right. `/` is not prerendered. I'd hesitate to do it because it may slow down client-side rendering app.

**Comment by dai-shi** [comment]
What I could do is to add a non-default option to support prerendering `/`.

**Comment by gionatan-lombardi** [comment]
Yes, I think it's the best way.

**Comment by dai-shi** [comment]
@gionatan-lombardi As I looked into the code, it's not trivial to fix it. I may need your help for testing.

**Comment by gionatan-lombardi** [comment]
@dai-shi I've done it in my project and it's working correctly. If you wish I can do a fork with tests so you can view the mods.

**Comment by dai-shi** [comment]
@gionatan-lombardi Cool. I'd like to take a look, if you don't mind taking time for it.

**Comment by gionatan-lombardi** [comment]
@dai-shi I've put the code and the test in a Pull Request #7.

**Comment by dai-shi** [comment]
closed by #7.
